#!/bin/bash
set -euo pipefail

handle_error() {
    echo "An error occurred while setting sparse checkout. Exiting..."
    exit 1
}

# Trap any errors and call the error handling function
trap 'handle_error' ERR

# Make sure github.com is in known hosts
ssh-keyscan github.com >> ~/.ssh/known_hosts

# Don't clone the repo if the checkout directory exists
if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
  echo "Checkout directory exists. Skipping clonning the repo..."
  pwd && ls -lah
  # Similar to the standard global chechout hook on the agent
  git clean -ffxdq
  echo "Fetch and checkout remote branch ${BUILDKITE_COMMIT} commit"
  git fetch -v --prune -- origin $BUILDKITE_COMMIT
  git checkout -f $BUILDKITE_COMMIT
  echo "Cleaning again to catch any post-checkout changes"
  git clean -ffxdq
  echo "Checking to see if Git data needs to be sent to Buildkite"
  buildkite-agent meta-data exists buildkite:git:commit
  exit 0
fi

# Blobless clone the repo without checking out the files
git clone --no-checkout --filter=blob:none $BUILDKITE_REPO $BUILDKITE_BUILD_CHECKOUT_PATH

# Set the sparse-checkout path
git sparse-checkout set $BUILDKITE_PLUGIN_GIT_SPARSE_CHECKOUT_PATTERN

# Perform the checkout
git checkout -f $BUILDKITE_COMMIT

# Disable git sparse checkout
git sparse-checkout disable
