#!/bin/bash
set -euo pipefail

handle_error() {
    echo "An error occurred while setting sparse checkout. Exiting..."
    exit 1
}

# Trap any errors and call the error handling function
trap 'handle_error' ERR

# Make sure github.com is in known hosts
ssh-keyscan github.com >> ~/.ssh/known_hosts

# Blobless clone the repo without checking out the files
git clone --no-checkout --filter=blob:none $BUILDKITE_REPO $BUILDKITE_BUILD_CHECKOUT_PATH

# Set the sparse-checkout path
git sparse-checkout set $BUILDKITE_PLUGIN_SPARSE_CHECKOUT_PATTERN

# Perform the checkout
git checkout
